Revert "bump »mockk« to 1.9.3"
This reverts commit b0b0bce2c29cfb3e19b401664f291fae7576c82a.

Run »MockK« on Java 11 throws exception:
```
java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor
```